CREATE DATABASE PAPELARIA;

USE PAPELARIA;

CREATE TABLE TIPOSUSUARIOS (
    ESTID INT AUTO_INCREMENT PRIMARY KEY,
    ESTNOME VARCHAR(100)
);

CREATE TABLE USUARIOS (
    USUID INT AUTO_INCREMENT PRIMARY KEY,
    USUNOME VARCHAR(100),
    USUCELULAR VARCHAR(20),
    USUCPF VARCHAR(11),
    USUCIDADE VARCHAR(100),
    USUTIPID INT,
    FOREIGN KEY (USUTIPID) REFERENCES TIPOSUSUARIOS(ESTID)
);

INSERT INTO TIPOSUSUARIOS (ESTNOME) VALUES
('CLIENTE'),
('FUNCIONARIO'),
('FORNECEDOR');